kind = "design"
previewPath = "/__mockup"
title = "Ocean"
version = "1.0.0"
id = "XegfDyZt7HqfW2Bb8Ghoy"

[[services]]
name = "Component Preview Server"
localPort = 8081
paths = ["/__mockup"]

[services.env]
PORT = "8081"
BASE_PATH = "/__mockup"

[services.development]
run = "pnpm --filter @workspace/mockup-sandbox dev"